#Dados do aluno

nota_aluno = 5
frequencia_aluno = 80


#Interface
print("\n---------------------------------------------------------------------------------\n")

print("EXIBIR DADOS DE ALUNO\n")
print("Nota:",nota_aluno,"\nFrequência:" ,frequencia_aluno,"%")


print("\n")

#Processamento e resultado
if nota_aluno >= 5 and frequencia_aluno >= 75:
    print("Condição:APROVADO") 


    

else:
    print("Condição:REPROVADO")



print("\n---------------------------------------------------------------------------------\n")